# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 447191fcb4f102c2c420af5853c7642a78fb4e20c2219c0c70a9c9a51a7dc5e10e57c74c0f2028965527ab8ccbe53355ad289bea9f4839159b1a5113bf0fd79b

test:
  secret_key_base: 5db9da7852fbb36f00e560ea584b30e7a68ee739c5067f1a177b9553ae5d2cadb8fc6e2d623886a052be8261b97df18eb8554327d2ccdeb89e912aa97dd027ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
